# Generated by Django 5.1.5 on 2025-02-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
